[package]
name = "jsonpath"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen-rust = { git = "https://github.com/bytecodealliance/wit-bindgen.git", rev = "60e3c5b41e616fee239304d92128e117dd9be0a7" }
jsonpath_lib = "0.3.0"
serde_json = "1.0.82"

[lib]
crate-type = ["cdylib"]
